apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-31T11:08:03Z"
  generateName: katafygio-56dfc84769-
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 56dfc84769
    release: katafygio
  name: katafygio-56dfc84769-4l8b6
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: katafygio-56dfc84769
    uid: dc7c1922-0046-4cb8-975c-870fb92b9186
spec:
  containers:
  - args:
    - --local-dir=/var/lib/katafygio/data
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:y8
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: tmp
      name: katafygio-data
    - mountPath: /etc/katafygio
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vs5vt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
  serviceAccount: katafygio
  serviceAccountName: katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: katafygio-data
    persistentVolumeClaim:
      claimName: katafygio
  - configMap:
      defaultMode: 420
      name: katafygio-config
    name: config-volume
  - name: kube-api-access-vs5vt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T11:08:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T11:09:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T11:09:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T11:08:03Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://306147cd32835bb66e1f2216e49f8acd184479d6ffd40c45f93dd098fddb8d5d
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:y8
    imageID: docker-pullable://svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio@sha256:fd5c0870ddc0ad9f21e35e2008658431781bdd96c8844d1055a962407f446d9e
    lastState: {}
    name: katafygio
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-31T11:08:34Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.1.10
  podIPs:
  - ip: 10.244.1.10
  qosClass: BestEffort
  startTime: "2024-01-31T11:08:03Z"
